// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.5

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type PayHTTPServer interface {
	CreatePay(context.Context, *PayCreateRequest) (*PayCreateReply, error)
}

func RegisterPayHTTPServer(s *http.Server, srv PayHTTPServer) {
	r := s.Route("/")
	r.GET("/create/pay", _Pay_CreatePay0_HTTP_Handler(srv))
}

func _Pay_CreatePay0_HTTP_Handler(srv PayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PayCreateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/pay.v1.Pay/CreatePay")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePay(ctx, req.(*PayCreateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PayCreateReply)
		return ctx.Result(200, reply)
	}
}

type PayHTTPClient interface {
	CreatePay(ctx context.Context, req *PayCreateRequest, opts ...http.CallOption) (rsp *PayCreateReply, err error)
}

type PayHTTPClientImpl struct {
	cc *http.Client
}

func NewPayHTTPClient(client *http.Client) PayHTTPClient {
	return &PayHTTPClientImpl{client}
}

func (c *PayHTTPClientImpl) CreatePay(ctx context.Context, in *PayCreateRequest, opts ...http.CallOption) (*PayCreateReply, error) {
	var out PayCreateReply
	pattern := "/create/pay"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/pay.v1.Pay/CreatePay"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
