service:
  name: project_name
  version: 1.0.0

data:
  nacos:
    addr: food-menu.proce.top
    port: 8848
    namespace_id: 4cc2d790-0f82-4a4a-91ad-217c086d6d48
    log_rotate_time: 1h
    log_max_age: 3
    log_level: debug
    cluster_name: DEFAULT
    group_name: DEFAULT_GROUP
    weight: 10